### ISSUE TITLE
Some trouble in NAMD input file when I use pyreweighting

### ISSUE THREAD

**Issue by chandler103** [MiaoLab20/PyReweighting#6]

**Comment by MiaoLab20** [comment]
You may find how to prepare weights.dat from NAMD log file for PyReweighting website: https://www.med.unc.edu/pharm/miaolab/resources/pyreweighting/


# For NAMD simulation:
# grep “ACCELERATED MD” namd.log | awk ‘NR%1==0’ | awk ‘{print $6/(0.001987*300)” ” $4 ” ” $6 ” “$8}’ > weights.dat

Best,
Yinglong

Yinglong Miao, Ph.D.
Associate Professor
Computational Medicine Program and
Department of Pharmacology
University of North Carolina - Chapel Hill
Tel: 1-919-962-5696
http://miaolab.org

On Apr 28, 2024, at 9:54 PM, chentyuu ***@***.***> wrote:



Hello, Dr Miao:
I have some problem in pyreweighting about "weights.dat". I don't know which one is dV that I should take in, and the column you provided seems dosen't match NAMD's log file.
The photo below is a output file in NAMD's GaMD. Can you point out which column I should take in weights.dat ?

Thank you very much !!!
NAMD.png (view on web)<https://github.com/MiaoLab20/pyreweighting/assets/60853163/e81e865a-9aae-4604-add8-9493f4a4abd2>

**Comment by chandler103** [comment]
Thanks ! Dr Miao :
    I generate PMF successfully. And I find it that the column in wak command should be "$10/(0.001987*300) $2 $10". Maybe the format of log file generated by NAMD had been changed for a while.
    Thanks very much for your reply!!!
